server:
  port: 8761
spring:
  application:
    name: eureka-server
  cloud:
    gateway:
      routes:
      - id: eureka
        uri: lb://eureka-server
        predicates:
        - Path=/eureka/**
        filters:
        - StripPrefix=1
        - name: RewritePath
          args:
            regexp: "/eureka/(?<path>.*)"
            replacement: "/${path}"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 0